CREATE OR REPLACE TRIGGER CALCULER_M
AFTER INSERT ON RESERVER
FOR EACH ROW 
    DECLARE
        M RESERVER.MONTANT%TYPE;  
        SOLDE UTILISATEUR.SOLDE%TYPE;  
        ID_UTIL UTILISATEUR.ID_UTILISATEUR%TYPE; 
        PRIX_P ITINERAIRE.PRIX%TYPE;
    BEGIN
        SELECT PRIX INTO PRIX_P
        FROM ITINERAIRE
        WHERE ID_ITINERAIRE=:NEW.ID_ITINERAIRE;
        IF :NEW.CLASSE = 1 THEN   
            M := (PRIX_P + 8) * :NEW.NOMBRE_PASSAGERS;  
        ELSIF :NEW.CLASSE = 3 THEN   
            M := (PRIX_P + 3) * :NEW.NOMBRE_PASSAGERS;  
        ELSE  
            M := PRIX_P * :NEW.NOMBRE_PASSAGERS;  
        END IF;  

        SELECT SOLDE, U.ID_UTILISATEUR INTO SOLDE, ID_UTIL   
        FROM UTILISATEUR U  
        WHERE U.ID_UTILISATEUR = :NEW.ID_UTILISATEUR;  

        IF SOLDE >= 100 THEN  
            M := M * 0.95;  
            DBMS_OUTPUT.PUT_LINE('SOLDE DE 5% EST REALISEE POUR L UTILISATEUR ' || :NEW.ID_UTILISATEUR);  
        END IF;  

        DBMS_OUTPUT.PUT_LINE('ID_RESERVATION ' || :NEW.ID_RESERVATION || ' PRIX ' || PRIX_P || ' NOMBRE_PASSAGERS ' || :NEW.NOMBRE_PASSAGERS || ' CLASSE ' || :NEW.CLASSE || ' montant ' || M);  

        --UPDATE RESERVER  
        --SET MONTANT = M  
        --WHERE ID_RESERVATION = ID_RES; 
END;
