CREATE OR REPLACE PACKAGE BODY GESTION_RECLAMATION
IS
    PROCEDURE AFFICHER_RECLAMATION
    (ID_R RECLAMATION.ID_RECLAMATION%TYPE)
    IS
        ID_I RECLAMATION.ID_ITINERAIRE%TYPE;
        NOM_U UTILISATEUR.NOM%TYPE;
        PRENOM_U UTILISATEUR.PRENOM%TYPE;
        DES RECLAMATION.DESCRIP%TYPE;
    BEGIN
        SELECT ID_ITINERAIRE,DESCRIP INTO ID_I,DES
        FROM RECLAMATION
        WHERE ID_RECLAMATION=ID_R;
        SELECT NOM,PRENOM INTO NOM_U,PRENOM_U
        FROM UTILISATEUR U,RECLAMATION R
        WHERE U.ID_UTILISATEUR=R.ID_UTILISATEUR AND R.ID_RECLAMATION=ID_R;
        DBMS_OUTPUT.PUT_LINE('Reclamation : '||ID_R||' éctcrite par l utilisateur: '||NOM_U||' '||PRENOM_U||'. Description: '||DES);
    END AFFICHER_RECLAMATION;
    
    PROCEDURE MISE_A_JOUR_REC
    (ID_R RECLAMATION.ID_RECLAMATION%TYPE)
    IS
    BEGIN
    UPDATE RECLAMATION
    SET STATUT='résolu'
    WHERE ID_RECLAMATION=ID_R;
    DBMS_OUTPUT.PUT_LINE(ID_R||' est résolue.');
    END MISE_A_JOUR_REC;

    PROCEDURE AJOUTER_RECLAMATION
    (ID_R RECLAMATION.ID_RECLAMATION%TYPE,ID_U RECLAMATION.ID_UTILISATEUR%TYPE,ID_I RECLAMATION.ID_ITINERAIRE%TYPE,DES RECLAMATION.DESCRIP%TYPE)
    IS
        ID_ITI RECLAMATION.ID_ITINERAIRE%TYPE;
        ITI_NOT_FOUND EXCEPTION;
    BEGIN
        SELECT ID_ITINERAIRE INTO ID_ITI
        FROM ITINERAIRE
        WHERE ID_ITINERAIRE=ID_I;
        IF (ID_ITI IS NULL) THEN RAISE ITI_NOT_FOUND;
        ELSE
            INSERT INTO RECLAMATION(ID_RECLAMATION,ID_UTILISATEUR,ID_ITINERAIRE,DESCRIP,DATE_RECLAMATION,STATUT)
            VALUES(ID_R,ID_U,ID_I,DES,SYSDATE,'en cours');
            DBMS_OUTPUT.PUT_LINE('Reclamation ajoutée avec succes');
        END IF;

        EXCEPTION
        WHEN ITI_NOT_FOUND THEN DBMS_OUTPUT.PUT_LINE('Le voyage saisi est inexistant.');
    END AJOUTER_RECLAMATION;
END GESTION_RECLAMATION;
