CREATE OR REPLACE PACKAGE BODY GESTION_ANNONCE
IS
    PROCEDURE AFFICHER_ANONCE
    (ID_A ANNONCE.ID_ANONCE%TYPE)
    IS
        ID_I ANNONCE.ID_ITINERAIRE%TYPE;
        TITRE ANNONCE.TITRE%TYPE;
        DES ANNONCE.DESCRIP%TYPE;
    BEGIN
        SELECT ID_ITINERAIRE, TITRE, DESCRIP INTO ID_I,TITRE,DES
        FROM ANNONCE
        WHERE ID_ANONCE=ID_A;
        DBMS_OUTPUT.PUT_LINE('Annonce: '||ID_A||' Titre: '||TITRE||' Description: '||DES);
    END AFFICHER_ANONCE;

    PROCEDURE SUPPRIMER_ANONCE
    (ID_A ANNONCE.ID_ANONCE%TYPE)
    IS
    BEGIN
        DELETE FROM ANNONCE
        WHERE ID_ANONCE=ID_A;
    END SUPPRIMER_ANONCE;
END GESTION_ANNONCE;
