CREATE OR REPLACE PACKAGE GESTION_PAIEMENT
IS
    PROCEDURE ASSOCIER_MONTANT
    (ID_RES RESERVER.ID_RESERVATION%TYPE,PRIX_P ITINERAIRE.PRIX%TYPE,NB RESERVER.NOMBRE_PASSAGERS%TYPE,CL RESERVER.CLASSE%TYPE);
    PROCEDURE REMPLIR_BILLET
    (ID_R RESERVER.ID_RESERVATION%TYPE,ID_B NUMBER);
END GESTION_PAIEMENT;
