CREATE OR REPLACE PACKAGE GESTION_RECLAMATION
IS
    PROCEDURE AFFICHER_RECLAMATION
    (ID_R RECLAMATION.ID_RECLAMATION%TYPE);
    PROCEDURE MISE_A_JOUR_REC
    (ID_R RECLAMATION.ID_RECLAMATION%TYPE);
    PROCEDURE AJOUTER_RECLAMATION
    (ID_R RECLAMATION.ID_RECLAMATION%TYPE,ID_U RECLAMATION.ID_UTILISATEUR%TYPE,ID_I RECLAMATION.ID_ITINERAIRE%TYPE,DES RECLAMATION.DESCRIP%TYPE);
END GESTION_RECLAMATION;
