CREATE OR REPLACE TRIGGER MISE_A_JOUR_ANNONCE_ITINERAIRE_DELETE
AFTER DELETE ON ITINERAIRE
FOR EACH ROW 
DECLARE
    LAST_PREV_ID ANNONCE.ID_ANONCE%TYPE;
    DES ANNONCE.DESCRIP%TYPE;
    TYP ANNONCE.TYP%TYPE;
    TITRE ANNONCE.TITRE%TYPE;
BEGIN
    SELECT NVL(MAX(ID_ANONCE), 0) INTO LAST_PREV_ID
    FROM ANNONCE;
    DES := 'Le voyage avec l itinéraire ' || TO_CHAR(:OLD.ID_ITINERAIRE) || ' a été annulé.';
        TYP := 'Annulation';
    TITRE := 'Annonce d annulation';
    INSERT INTO ANNONCE (ID_ANONCE, ID_ITINERAIRE, TITRE, DESCRIP, DATE_ANONCE, TYP)
    VALUES (LAST_PREV_ID + 1, :OLD.ID_ITINERAIRE, TITRE, DES, SYSDATE, TYP);
END MISE_A_JOUR_ANNONCE_ITINERAIRE;
