CREATE OR REPLACE TRIGGER MISE_A_JOUR_ANNONCE_ITINERAIRE_UPDATE
AFTER UPDATE ON ITINERAIRE
FOR EACH ROW 
DECLARE
    LAST_PREV_ID ANNONCE.ID_ANONCE%TYPE;
    DES ANNONCE.DESCRIP%TYPE;
    TYP ANNONCE.TYP%TYPE;
    TITRE ANNONCE.TITRE%TYPE;
BEGIN
    SELECT NVL(MAX(ID_ANONCE), 0) INTO LAST_PREV_ID
    FROM ANNONCE;
    IF :OLD.DATE_DEPART != :NEW.DATE_DEPART THEN
        DES := 'La date du voyage ' || TO_CHAR(:NEW.ID_ITINERAIRE) || ' est modifiée à : ' || TO_CHAR(:NEW.DATE_DEPART, 'DD/MM/YYYY');
    ELSIF :OLD.PRIX != :NEW.PRIX THEN
        DES := 'Le prix du voyage ' || TO_CHAR(:NEW.ID_ITINERAIRE) || ' est modifié à : ' || :NEW.PRIX;
    END IF;
    TYP := 'Modification';
    TITRE := 'Annonce de modification';
    INSERT INTO ANNONCE (ID_ANONCE, ID_ITINERAIRE, TITRE, DESCRIP, DATE_ANONCE, TYP)
    VALUES (LAST_PREV_ID + 1, :NEW.ID_ITINERAIRE, TITRE, DES, SYSDATE, TYP);
END MISE_A_JOUR_ANNONCE_ITINERAIRE;
