SELECT NOM,PRENOM,COUNT(R.ID_ITINERAIRE) AS NOMBRE_DE_VOYAGE
FROM RESERVER R,UTILISATEUR U
WHERE R.ID_UTILISATEUR=U.ID_UTILISATEUR AND UPPER(ETAT)='PAYEE'
GROUP BY NOM,PRENOM;

SELECT U.ID_UTILISATEUR,NOM,PRENOM, COUNT(R.ID_RESERVATION) AS NOMBRE_VOYAGES  
FROM UTILISATEUR U, RESERVER R  
WHERE U.ID_UTILISATEUR = R.ID_UTILISATEUR AND UPPER(ETAT)='PAYEE'
GROUP BY  U.ID_UTILISATEUR, U.NOM, U.PRENOM  
HAVING COUNT(R.ID_RESERVATION) = (SELECT MAX(COUNT(ID_RESERVATION)) 
                                  FROM RESERVER  
                                  WHERE UPPER(ETAT)='PAYEE'
                                  GROUP BY ID_UTILISATEUR)

DECLARE  
    CURSOR VOYAGE IS SELECT * FROM ITINERAIRE;  
    NB NUMBER;  
    HEURE HORAIRE.HEURE_DEPART%TYPE; 
    CURRENT_ID ITINERAIRE.ID_ITINERAIRE%TYPE; 
BEGIN  
    FOR ITI IN VOYAGE LOOP  
        SELECT COUNT(*) INTO NB  
        FROM RESERVER  
        WHERE ID_ITINERAIRE = ITI.ID_ITINERAIRE;
        IF NB = 0 THEN 
            DBMS_OUTPUT.PUT_LINE('Reservation numéro: ' || ITI.ID_ITINERAIRE || ' non reservé'); 
        ELSE
            SELECT HEURE_DEPART INTO HEURE  
            FROM HORAIRE H  
            WHERE H.ID_ITINERAIRE = ITI.ID_ITINERAIRE; 
            DBMS_OUTPUT.PUT_LINE('Reservation numéro: ' || ITI.ID_ITINERAIRE ||' Heure du départ: ' || HEURE ||' Lieu de départ: ' || ITI.DEPART ||' Lieu d arrivée: ' || ITI.ARRIVEE);  
        END IF;  
    END LOOP;  
END;


SELECT MT.ID_TRANSPORT,MT.TYPE_VEH, MT.MATRICULE, I.ID_ITINERAIRE, I.DATE_DEPART, I.DEPART, I.ARRIVEE, I.DISTANCE, I.DUREE, I.PRIX
FROM MOYEN_TRANSPORT MT, ITINERAIRE I
WHERE MT.ID_TRANSPORT = I.ID_TRANSPORT;


SELECT ID_TRANSPORT,COUNT(ID_ITINERAIRE)
FROM ITINERAIRE
WHERE DATE_DEPART<=SYSDATE
GROUP BY ID_TRANSPORT;

DECLARE
    V_ID_UTILISATEUR UTILISATEUR.ID_UTILISATEUR%TYPE;
    V_NOM UTILISATEUR.NOM%TYPE;
    V_PRENOM UTILISATEUR.PRENOM%TYPE;
    V_SOLDE UTILISATEUR.SOLDE%TYPE;
    CURSOR CUR_ITINERAIRES IS SELECT ID_ITINERAIRE FROM ITINERAIRE;
    CURSOR CUR_MAX_SOLDE (P_ID_ITINERAIRE ITINERAIRE.ID_ITINERAIRE%TYPE) IS
        SELECT U.ID_UTILISATEUR, U.NOM, U.PRENOM, U.SOLDE
        FROM UTILISATEUR U
        WHERE U.ID_UTILISATEUR IN (
            SELECT R.ID_UTILISATEUR
            FROM RESERVER R
            WHERE R.ID_ITINERAIRE = P_ID_ITINERAIRE)
        ORDER BY U.SOLDE DESC
        FETCH FIRST 1 ROWS ONLY;

BEGIN
    FOR IT IN CUR_ITINERAIRES LOOP
        OPEN CUR_MAX_SOLDE(IT.ID_ITINERAIRE);
        FETCH CUR_MAX_SOLDE INTO V_ID_UTILISATEUR, V_NOM, V_PRENOM, V_SOLDE;
        IF CUR_MAX_SOLDE%FOUND THEN
            DBMS_OUTPUT.PUT_LINE('ITINÉRAIRE: ' || IT.ID_ITINERAIRE ||' UTILISATEUR: ' || V_ID_UTILISATEUR ||' NOM: ' || V_NOM ||' PRÉNOM: ' || V_PRENOM ||' SOLDE: ' || V_SOLDE);
        END IF;
        CLOSE CUR_MAX_SOLDE;
    END LOOP;
END;


CREATE OR REPLACE FUNCTION CALCULER (ID_MOY MOYEN_TRANSPORT.ID_TRANSPORT%TYPE) RETURN NUMBER
IS NB NUMBER;
BEGIN
        SELECT COUNT(ID_TRANSPORT) INTO NB
        FROM ITINERAIRE 
        WHERE ID_TRANSPORT=ID_MOY;
        RETURN NB;
END CALCULER;

DECLARE 
    CURSOR MOYEN IS SELECT * FROM MOYEN_TRANSPORT;
BEGIN
    FOR MOY IN MOYEN LOOP
    DBMS_OUTPUT.PUT_LINE('ID du moyen du transport: '||MOY.ID_TRANSPORT||' Type de véhicule: '||MOY.TYPE_VEH||' Matricule: '||MOY.MATRICULE||' Nombre de reservations: '||CALCULER(MOY.ID_TRANSPORT));
    END LOOP;
END;
