CREATE TABLE UTILISATEUR (
    ID_UTILISATEUR NUMBER PRIMARY KEY,
    NOM VARCHAR2(50),
    PRENOM VARCHAR2(50),
    EMAIL VARCHAR2(100),
    SOLDE NUMBER
);

CREATE TABLE MOYEN_TRANSPORT (
    ID_TRANSPORT NUMBER PRIMARY KEY,
    TYPE_VEH VARCHAR2(50),
    MATRICULE VARCHAR2(20) UNIQUE,
    CAPACITE NUMBER
);

CREATE TABLE ITINERAIRE (
    ID_ITINERAIRE NUMBER PRIMARY KEY,
    ID_TRANSPORT NUMBER REFERENCES MOYEN_TRANSPORT(ID_TRANSPORT),
    DATE_DEPART DATE,
    DEPART VARCHAR2(50),
    ARRIVEE VARCHAR2(50),
    DISTANCE NUMBER(10,3),
    DUREE NUMBER,
    NOMBRE_ACTUEL NUMBER,
    PRIX NUMBER(10,3)
);

CREATE TABLE RESERVER (
    ID_RESERVATION NUMBER PRIMARY KEY,
    ID_UTILISATEUR NUMBER REFERENCES UTILISATEUR(ID_UTILISATEUR),
    ID_ITINERAIRE NUMBER REFERENCES ITINERAIRE(ID_ITINERAIRE),
    NOMBRE_PASSAGERS NUMBER,
    DATE_RESERVATION DATE,
    ETAT VARCHAR2(20),
    CLASSE VARCHAR2(20),
    MONTANT NUMBER(10,3)
);

CREATE TABLE BILLET (
    ID_BILLET NUMBER PRIMARY KEY,
    ID_RESERVATION NUMBER REFERENCES RESERVER(ID_RESERVATION)
);

CREATE TABLE ANNONCE (
    ID_ANONCE NUMBER PRIMARY KEY,
    ID_ITINERAIRE NUMBER REFERENCES ITINERAIRE(ID_ITINERAIRE),
    TITRE VARCHAR2(100),
    DESCRIP VARCHAR2(255),
    DATE_ANONCE DATE,
    TYP VARCHAR2(20)
);

CREATE TABLE RECLAMATION (
    ID_RECLAMATION NUMBER PRIMARY KEY,
    ID_UTILISATEUR NUMBER REFERENCES UTILISATEUR(ID_UTILISATEUR),
    ID_ITINERAIRE NUMBER REFERENCES ITINERAIRE(ID_ITINERAIRE),
    DESCRIP VARCHAR2(200),
    DATE_RECLAMATION DATE,
    STATUT VARCHAR2(20) 
);

CREATE TABLE HORAIRE (
    ID_HORAIRE NUMBER PRIMARY KEY,
    ID_ITINERAIRE NUMBER REFERENCES ITINERAIRE(ID_ITINERAIRE),
    HEURE_DEPART TIMESTAMP
);
