DECLARE 
    CURSOR ANN_AFFICHER IS SELECT ID_ANONCE
                           FROM ANNONCE AN,ITINERAIRE I
                           WHERE AN.ID_ITINERAIRE=I.ID_ITINERAIRE AND DATE_DEPART>=SYSDATE;
    CURSOR ANN_SUPPRIMER IS SELECT ID_ANONCE
                           FROM ANNONCE AN,ITINERAIRE I
                           WHERE AN.ID_ITINERAIRE=I.ID_ITINERAIRE AND DATE_DEPART<=SYSDATE;
BEGIN
    FOR A_F IN ANN_AFFICHER LOOP
        GESTION_ANNONCE.AFFICHER_ANONCE(A_F.ID_ANONCE);
    END LOOP;
    FOR A_S IN ANN_SUPPRIMER LOOP
        GESTION_ANNONCE.SUPPRIMER_ANONCE(A_S.ID_ANONCE);
        DBMS_OUTPUT.PUT_LINE('Suppression des annonces resussite');
    END LOOP;
END;
