DECLARE 
    CURSOR RES IS SELECT ID_RESERVATION
                  FROM RESERVER;
    CURSOR UTILS IS SELECT ID_UTILISATEUR FROM UTILISATEUR;
    ID_R RESERVER.ID_RESERVATION%TYPE;
    ID_U RESERVER.ID_UTILISATEUR%TYPE;
    ID_IT RESERVER.ID_ITINERAIRE%TYPE;
    NB RESERVER.NOMBRE_PASSAGERS%TYPE;
    CL RESERVER.CLASSE%TYPE;

BEGIN
    FOR R IN RES LOOP
        GESTION_RESERVATION.VERIFIER_RESERVATION(R.ID_RESERVATION);
    END LOOP; 
    FOR U IN UTILS LOOP
        GESTION_RESERVATION.ASSOCIER_SOLDE(U.ID_UTILISATEUR);       
    END LOOP;
    ID_R:=:ID_RESERVATION;
    ID_U:=:ID_UTILISATEUR;
    ID_IT:=:ID_ITINERAIRE;
    NB:=:NOMBRE_PERSONES;
    CL:=:CLASSE;
    GESTION_RESERVATION.AJOUTER_RESERVATION(ID_R,ID_U,ID_IT,NB,SYSDATE,CL);

END;
