DECLARE
    CURSOR RES IS SELECT ID_RESERVATION,NOMBRE_PASSAGERS,CLASSE FROM RESERVER;
    PRIX_P ITINERAIRE.PRIX%TYPE;
    CURSOR BILLETS_A_REMPLIR IS SELECT ID_RESERVATION FROM RESERVER WHERE UPPER(ETAT)='PAYEE';
    ID_B NUMBER;
BEGIN
    FOR R IN RES LOOP
        SELECT PRIX INTO PRIX_P
        FROM RESERVER RE, ITINERAIRE I
        WHERE R.ID_RESERVATION=RE.ID_RESERVATION AND RE.ID_ITINERAIRE=I.ID_ITINERAIRE;
        GESTION_PAIEMENT.ASSOCIER_MONTANT(R.ID_RESERVATION,PRIX_P,R.NOMBRE_PASSAGERS,R.CLASSE);  
    END LOOP;
    SELECT MAX(ID_BILLET) INTO ID_B
    FROM BILLET;
    IF ID_B IS NULL THEN
        ID_B:=0;
    END IF;
    FOR B IN BILLETS_A_REMPLIR LOOP
        ID_B:=ID_B+1;
        GESTION_PAIEMENT.REMPLIR_BILLET(B.ID_RESERVATION,ID_B);
        DBMS_OUTPUT.PUT_LINE('Insertion dans la table BILLET reussite');
    END LOOP;

END;
