DECLARE
    CURSOR REC_AFF IS SELECT ID_RECLAMATION FROM RECLAMATION WHERE UPPER(STATUT)='EN COURS';
    CURSOR REC_UPDATE IS SELECT ID_RECLAMATION FROM RECLAMATION WHERE ID_ITINERAIRE=110;
    ID_U RECLAMATION.ID_UTILISATEUR%TYPE;
    ID_I RECLAMATION.ID_ITINERAIRE%TYPE;
    DES RECLAMATION.DESCRIP%TYPE;
    ID_NEW_R RECLAMATION.ID_RECLAMATION%TYPE;
BEGIN
    FOR R_A IN REC_AFF LOOP
        GESTION_RECLAMATION.AFFICHER_RECLAMATION(R_A.ID_RECLAMATION);
    END LOOP;
    FOR R_UP IN REC_UPDATE LOOP
        GESTION_RECLAMATION.MISE_A_JOUR_REC(R_UP.ID_RECLAMATION);
    END LOOP;
    SELECT MAX(ID_RECLAMATION) INTO ID_NEW_R
    FROM RECLAMATION;
    ID_U:=:ID_UTILISATEUR;
    ID_I:=:ID_ITINERAIRE;
    DES:=:RECLAMATION_DESCRIPTION;
    GESTION_RECLAMATION.AJOUTER_RECLAMATION(ID_NEW_R+1,ID_U,ID_I,DES);
END;
