CREATE OR REPLACE TRIGGER VERIFIER_HEURE
BEFORE INSERT ON RESERVER 
FOR EACH ROW
BEGIN
    IF TO_NUMBER(TO_CHAR(SYSDATE, 'HH24')) >= 19 OR TO_NUMBER(TO_CHAR(SYSDATE, 'HH24')) < 5 THEN
        DBMS_OUTPUT.PUT_LINE('Nous sommes hors service maintenant.');
        RAISE_APPLICATION_ERROR(-20001, 'Insertion non autorisée entre 19h00 et 5h00');
    END IF;
END;
